version: '3'
services:
  app:
    build: .
    container_name: app
    image: nodejs-esm
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
      - ./dist:/app/dist
      - ./local:/app/local
    ports:
      - "8080:8080"
    tty: true
